### ISSUE TITLE
Would you be up for formalizing a schema design?

### ISSUE THREAD

**Issue by howardroark** [xodigital/ArtVandelay#10]
Hey!
 
I love the name!  Fun and memorable ;) I have been wanting something like this for some time. 

Looks like your current import/export object is a literal map of the current craft object structure, which makes a lot of sense.  I have a thought/idea/wish to offer...

What would be awesome is if the object itself was an easy to read/write schema.  Less of a literal translation and more of a "common sense" mapping.  That way you could just update it in an editor as it evolves.

Something like...

```
{
  "Contact": {
    "type": "Single",
    "fields": {
      "Phone": {
      	"type":"Text",
      	"options": ...
     },
      "Address": {
      	"type":"Rich Text",
      	"options": ...
     }
  },
  "Event": {
      "type": "Channel",
      "fields": {
        "Gallery": {
          "type": "Matrix",
          "fields": {
            "Image Title": {
              "type": "Text",
              "options": ...
            },
            "Image": {
              "type": "Asset",
              "options":..
            }
          }
        }
      }
    }
  }
}
```

I don't mean to be presumptuous, but I thought I would check to see if you may be up to go this direction.   I find that if you design the schema first, then you can use it as your roadmap.  Who knows maybe Craft itself may be up for adopting something after a few iterations.

**Comment by wiso1234** [comment]
Hey Howard,

At the moment what the code does is dump crafts internal format in json format. Then at the import end we just turn that json back into the native craft object.

The beauty of this approach is it automatically dumps the entire craft object, so if the craft team add new attributes or field types or whatever, Art will continue to work without needing updates.

**Comment by howardroark** [comment]
Great points!  Yeah I guess it would only really work if Craft itself had a simple JSON schema to design site data entry.
