### ISSUE TITLE
Wondering about command line option.

### ISSUE THREAD

**Issue by howardroark** [xodigital/ArtVandelay#12]
Hey!  

Looking around the code there appears to be a command line option.  I was just curious about how that works? I would love to be able to supply an object with a boilerplate for different types of sites that I can active in a build process.

Thanks!

**Comment by thoaionline** [comment]
Hey @howardroark, Craft use Yii's CLI component so you can simply run:

```
php ./craft/app/etc/console/yiic
```

to see a list of available commands in your project.

**Comment by howardroark** [comment]
Thanks!
