### ISSUE TITLE
Support for Matrix blocks

### ISSUE THREAD

**Issue by engram-design** [xodigital/ArtVandelay#2]
Is there support for exporting the blocks inside a Matrix field? Currently, it only exports the Matrix field, not the block it contains as well.

````
{
  "assets": [],
  "categories": [],
  "fields": {
      "pageBody": {
        "name": "Body",
        "context": "global",
        "instructions": "",
        "translatable": 0,
        "type": "Matrix",
        "settings": {
          "maxBlocks": null
        }
      }
  },
  "globals": [],
  "sections": [],
  "tags": []
}
````

**Comment by noisysocks** [comment]
Thanks for reporting this @engram-design! The plugin should handle Matrix types properly now.

**Comment by engram-design** [comment]
Thanks to you @noisysocks - that'll really assist with import/export! :)
