### ISSUE TITLE
JSON_PRETTY_PRINT "null"

### ISSUE THREAD

**Issue by blockscms** [xodigital/ArtVandelay#4]
I'm Japanese. so not well english, sorry.
I use "Art Vandelay 1.0.2",
Afte export the craft field , it appears as " null" .

This is an error log
 "Use of undefined constant JSON_PRETTY_PRINT - assumed 'JSON_PRETTY_PRINT' (/[my host]/craft/plugins/artvandelay/models/ArtVandelay_ExportedDataModel.php:46)"

("my host" mean my server host.)

There 33 all the fields , of which matrix Fields There are 17.

Is this a bug ?

**Comment by mdcpepper** [comment]
Check the version of PHP running on the server, `JSON_PRETTY_PRINT` needs at least PHP 5.4.

**Comment by blockscms** [comment]
OH!
Thank you.
This problem could be solved.
